sudo: required
language: generic
services:
  - docker

before_install:
  - cd ./complex
  - docker build -t bifidokk/bbot .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bifidokk/bbot