on: [push]
name: Build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: postgres:14.0
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bbot
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - run: go mod download
      - name: Build
        run: go build ./cmd/app/main.go
      - uses: ariga/setup-atlas@v0
      - uses: ariga/atlas-action/migrate/apply@v1
        with:
          dir: 'file://migrations'
          url: "postgres://postgres:postgres@localhost:5432/bbot?search_path=public&sslmode=disable"