name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bifidokk/bbot:latest

      - name: Run built image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            docker pull bifidokk/bbot:latest
            docker stop bbot
            docker rm -f bbot
            docker run --name bbot --env BBOT_TOKEN=$BBOT_TOKEN --env BBOT_BASE_URL=$BBOT_BASE_URL --env BBOT_WEBHOOK_URL=$BBOT_WEBHOOK_URL --env BBOT_WEBHOOK_PATH=$BBOT_WEBHOOK_PATH -p $BBOT_PORTS -d bifidokk/bbot:latest